### ISSUE TITLE
TODO: web, landing page

### ISSUE THREAD

**Issue by netzulo** [borjarg95/pushdown-generator#13]
# Description

- [ ] Refactor index to show landing page with information about **author**
- [ ] Add new route **/automatism** and server existing SPA at this route
- [ ] refactor JS nomenclature at **App.js** file

## Questions 

Intructions : *mark checkbox if agree, edit with `~text~` to deny lane*

- ~Can i edit Java sources to change names to english ?~
- ~Are you agree with new route ? `GET /automatism~

---

@borjarg95 ill PR this

**Comment by borjarg95** [comment]
As we talk, the names are going to keep in Spanish and the endpoint /automatism won't be created

**Comment by netzulo** [comment]
closed, have no sense then
