### ISSUE TITLE
TODO: make works CIs for github

### ISSUE THREAD

**Issue by netzulo** [borjarg95/pushdown-generator#2]
## Documentation

Need to be created all accounts for borjarg95 username and edit tokens included at README file

## TODOs

+ [x] Travis.ci : https://travis-ci.org/
qyS-hUwdZM9PegBPCnZMGA https://github.com/netzulo/pushdown-generator/commit/925d9031999033e08d2dc6c22e19c0c47c5cc61f
+ [x] Appveyor : https://ci.appveyor.com/signup
3xxoa0v87svm6l27m16o
+ [x] CircleCI: https://circleci.com/signup/
48ff0ecc6afba2cbe94acec8060e8d5115d7da61
+ [x] CodeClimate : https://codeclimate.com/dashboard
f6443902cc85c540ff3b0abd95bb5045294b5875

### Issues related

- #1 
---

*All CIs templates will be uploaded when users for all CIs are working*

**Comment by netzulo** [comment]
edited description, @borjarg95
